### ISSUE TITLE
Its not possible to set a new value at the root of the yaml

### ISSUE THREAD

**Issue by ysaakpr** [icza/dyno#3]
Because of the path cannot be empty, it cant add any new element to the root of the yaml.

say my yaml

```
field:
  test: 123
  test2: 12443
filed2: sdfsdf
```

What is the possibility of adding `field3` in the root of the yaml in this case?
